ref #94 ci on arch aur repo

diff --git a/.github/workflows/release-executable.yaml b/.github/workflows/release-executable.yaml
--- a/.github/workflows/release-executable.yaml
+++ b/.github/workflows/release-executable.yaml
@@ -95,7 +95,7 @@ jobs:
           mv "${BUILT_FILEPATH}" "${{ env.JOB_WORKDIR }}/${RELEASE_SRC_DIR}/"
           echo "RELEASE_SRC_DIR=${RELEASE_SRC_DIR}" >> $GITHUB_ENV
           echo "RELEASE_ASSET_FILENAME=${RELEASE_ASSET_FILENAME}" >> $GITHUB_ENV
-
+      
       # BSD tar on macOS: first 8MB of the file are sometimes all NUL byte
       # refs: https://github.com/actions/cache/issues/403 , https://github.com/rust-lang/cargo/issues/8603
       - name: Mitigate macOS tar bug
@@ -103,7 +103,7 @@ jobs:
         run: |
           sudo /usr/sbin/purge
       
-      - name: Create archive as release asset - Linux / macOS
+      - name: Create archive as release asset - Linux
         if: >
           matrix.target != 'aarch64-apple-darwin' &&
           matrix.target != 'x86_64-pc-windows-msvc'
@@ -111,7 +111,7 @@ jobs:
           cd "${{ env.JOB_WORKDIR }}"
           tar czf "../${RELEASE_ASSET_FILENAME}" "${RELEASE_SRC_DIR}"
       
-      - name: Create archive as release asset - Windows
+      - name: Create archive as release asset - Windows / macOS
         if: >
           matrix.target == 'aarch64-apple-darwin' ||
           matrix.target == 'x86_64-pc-windows-msvc'
@@ -123,3 +123,61 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: gh release upload ${{ github.ref_name }} ${RELEASE_ASSET_FILENAME}
+
+      # [ packaging ]
+      - name: ArchLinux AUR SSH and asset hash setup
+        if: matrix.target == 'x86_64-unknown-linux-gnu'
+        run: |
+          mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
+          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur_key
+          chmod 600 ~/.ssh/aur_key
+          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
+          chmod 600 ~/.ssh/known_hosts
+          echo -e "Host aur.archlinux.org\n  User aur\n  IdentityFile ~/.ssh/aur_key\n  StrictHostKeyChecking yes\n  LogLevel ERROR" >> ~/.ssh/config
+          chmod 600 ~/.ssh/config
+
+          RELEASE_ASSET_SHA256=$(sha256sum "${RELEASE_ASSET_FILENAME}" | awk '{print $1}')
+          echo "RELEASE_ASSET_SHA256=${RELEASE_ASSET_SHA256}" >> $GITHUB_ENV
+
+      - name: ArchLinux AUR update
+        if: matrix.target == 'x86_64-unknown-linux-gnu'
+        env:
+          AUR_REPO_URL: "ssh://aur@aur.archlinux.org/${{ env.PRODUCT_BASENAME }}.git"
+          AUR_DIR: "aur-repo-${{ github.run_id }}"
+        run: |
+          git clone "${AUR_REPO_URL}" "${AUR_DIR}"
+          cd "${AUR_DIR}"
+
+          sed -i "s/^pkgname=.*/pkgname=${{ env.PRODUCT_BASENAME }}/" PKGBUILD
+          sed -i "s/^pkgver=.*/pkgver=${{ github.ref_name }}/" PKGBUILD
+          sed -i "s/^sha256sums=(.*)/sha256sums=('${RELEASE_ASSET_SHA256}')/" PKGBUILD
+
+          docker run --rm \
+            -v "$(pwd)":/src \
+            archlinux:latest bash -c " \
+              useradd -m builduser && \
+              chown -R builduser:builduser /src && \
+              su - builduser -c 'cd /src && makepkg --printsrcinfo > .SRCINFO' \
+            "
+          sudo chown -R "$(id -u):$(id -g)" .
+
+          if ! git diff --quiet --exit-code; then
+            git config user.email "${{ secrets.AUR_EMAIL }}"
+            git config user.name "GitHub Actions AUR Updater"
+            
+            git add PKGBUILD .SRCINFO
+            git commit -m "${{ github.ref_name }}: new release update"
+
+            git push
+            echo "successfully pushed updates to AUR."
+          else
+            echo "no changes detected for AUR, skipping."
+          fi
+        
+      - name: ArchLinux AUR SSH clean up
+        if: always() && matrix.target == 'x86_64-unknown-linux-gnu'
+        run: |
+          rm -f ~/.ssh/aur_key
+          rm -f ~/.ssh/known_hosts
+        
